#goal definition
nav_msgs/Path path
string controller_id
---
#result definition
builtin_interfaces/Duration total_time
---
#feedback
float32 distance_to_goal
float32 speed
builtin_interfaces/Duration elapsed_time
