#goal definition
geometry_msgs/PoseStamped pose
string planner_id
---
#result definition
geometry_msgs/PoseStamped[] path
builtin_interfaces/Duration planning_time
---
#feedback
builtin_interfaces/Duration elapsed_time
